### PR TITLE
Feat/meps

### PR DESCRIPTION
**Pull request by jerabaul29**
@vkbo 

- add a couple of helper functions for selecting ranges of indexes based on coordinate bounds
- add an example of query to OpenDAP server

### CODE REVIEW

**Comment by jerabaul29** [comment]
A small note: for now the example queries a full field (for example, pressure at the surface) from the OpenDAP server, and then only once the full field has been obtained, performs the slicing locally. This means that more information than necessary is transmitted, and then some data are discarded. I have been trying to query only slices of interest from the server, but I need to dig a bit more on how such requests are performed, so will rather push an updated example later.

**Comment by jerabaul29** [comment]
mmh, wait a second, I found a notation inconsistency in the helper functions, fixing it now.

**Comment by jerabaul29** [comment]
Ok, the naming should be better now, ready from my side :) .

**Comment by jerabaul29** [comment]
Ok, I finally found how to retrieve a slice of a single field, transmitting only needed data: this can be performed with netCDF4, but one has to formulate the custom URL request by hand.

**Comment by jerabaul29** [comment]
@vkbo any comments on this? :)

**Review by vkbo — APPROVED** [review]

**Pull request merged**
